### ISSUE TITLE
Stromerzeugung um 5 Uhr

### ISSUE THREAD

**Issue by EmanuelLoos** [gvzdus/PVPrognose#3]
Ich versuche die Stromerzeugung einer kleinen PV-Anlage zu prognostizieren, schaffe es aber mit keiner Einstellung, um 5 Uhr eine andere Erzeugung als 0 Wattstunden als Ergebnis zu erhalten, obwohl es bei mir, aufgrund von der Ausrichtung und Höhe, zu einer solchen Erzeugung kommt. Auch verstehe ich das mit dem Horizont nicht so ganz. Und was ist eigentlich mit beispielsweise 8 Uhr gemeint, 8:00 Uhr bis 9:00 Uhr oder 7:00 Uhr bis 8:00 Uhr?
Bei solXpect kommen irgendwie mit den selben Einstellungen andere Werte heraus.

![Screenshot 2023-07-11 at 17-55-27 Energie – Home Assistant](https://github.com/gvzdus/PVPrognose/assets/29912739/f4449db0-8ea3-40da-8cfe-a6239e198a7d)
```
TIME			     WhGenFc	Temp	DirectRad   DiffRad ShortWave	SunAzi	SunEle
2023-07-09T00:00:00Z	  0	23.3	  0.0		  0.0	  0.0		  5.2	-16.3
2023-07-09T01:00:00Z	  0	21.8	  0.0		  0.0	  0.0		 19.4	-14.3
2023-07-09T02:00:00Z	  0	20.6	  0.0		  0.0	  0.0		 32.9	-10.2
2023-07-09T03:00:00Z	  0	19.6	  0.0		  0.0	  0.0		 45.6	 -4.2
2023-07-09T04:00:00Z	  0	19.2	  0.0		  0.0	  0.0		 57.3	  3.1
2023-07-09T05:00:00Z	  0	19.0	  0.0		  0.0	  0.0		 68.5	 11.5
2023-07-09T06:00:00Z	 20	18.6	 15.9		  4.0	  5.0		 79.4	 20.5
2023-07-09T07:00:00Z	241	20.0	200.4		 40.0	 67.0		 90.7	 29.9
2023-07-09T08:00:00Z	477	23.0	434.6		 72.0	191.0		103.2	 39.2
2023-07-09T09:00:00Z	572	25.3	591.4		 93.0	344.0		118.1	 48.0
2023-07-09T10:00:00Z	560	27.9	699.4		105.0	501.0		137.0	 55.5
2023-07-09T11:00:00Z	465	29.9	771.4		111.0	643.0		161.7	 60.4
2023-07-09T12:00:00Z	309	31.8	814.0		115.0	755.0		190.2	 61.0
2023-07-09T13:00:00Z	145	33.4	815.8		130.0	823.0		216.4	 57.3
2023-07-09T14:00:00Z	133	34.5	505.2		279.0	721.0		236.9	 50.4
2023-07-09T15:00:00Z	113	33.6	148.7		339.0	467.0		252.8	 41.9
2023-07-09T16:00:00Z	 83	27.5	 14.8		277.0	289.0		265.8	 32.6
2023-07-09T17:00:00Z	 77	20.0	 12.5		249.0	258.0		277.4	 23.2
2023-07-09T18:00:00Z	 37	22.2	  0.0		121.0	121.0		288.4	 14.0
2023-07-09T19:00:00Z	 41	21.6	 12.8		132.0	138.0		299.4	  5.4
2023-07-09T20:00:00Z	 31	22.6	 75.5		 90.0	114.0		310.9	 -2.3
2023-07-09T21:00:00Z	 21	22.3	125.8		 58.0	 79.0		323.3	 -8.7
2023-07-09T22:00:00Z	  4	21.6	 12.0		 11.0	 12.0		336.6	-13.4
2023-07-09T23:00:00Z	  0	21.2	  0.0		  0.0	  0.0		350.7	-16.1
```

```
#
# Position
longitude=16.3721
latitude=48.2085

planes=Balkon

# 0 = Nord, 90 Ost, ..
Balkon.azimuth=84
# Dachneigung
Balkon.tilt=74
# Kapazitaet DC
Balkon.capacity=1155
Balkon.cellsTempCoeff=-0.35
# Inverter:
Balkon.inverter=EFFEKTA
Balkon.albedo=0.3
Balkon.diffuseEfficiency=0.15
# Horizont:
# The PVGis5 horizon model is used: 
# A list of equal wide sectors, starting from North clockwise, representing the obstacle elevation angle
# E.g.: 36 Values means: First value is the obstacle angle at 0-9.9°
# The elevation might be followed by a 't' and a transparency, to reflect e.g. thin obstacles or trees
# 10t0.2 means: Up to 10° sun elevation, only 20% transparency for direct radiation
# horizon04 = 40°-49° Azimuth, Werte = Elevation, bis zu der eine Opazität von x angenommen wird (Default 0)
Balkon.horizon=0,0,0,0,0,7,8,8,8,8,8,9,9,9,9,10,10,10,10,20t0.15,40t0.15,70,70,70,70,70,70,70,70,70,70,70,70,70,0,0

EFFEKTA.maxpower=5000
```
Danke!

**Comment by gvzdus** [comment]
6 Uhr bedeutet: Von 5-6 Uhr gemessene Wattstunden. Das ist analog zum Datenmodel von OpenMeteo: Hier sind auch die Werte für Strahlungseintrag jeweils kumulierte Werte aus der "Vorherstunde".
Zum Horizont: Du hast 36 Werte angegeben (bis zum 't'). Daher entspricht jeder Wert einem Kreissegment von (360 / 36) = 10°. Also bei Dir: 0-50° (5x10°) kein Hindernis am Horizont, dann 7° von 50°-60°, u.s.w.
Hinter dem t können Werte von 0-1 für eine Teiltransparenz (Bäume, whatever) stehen, hier also 0.15 bei 2 Werten.
Lässt Du horizont ganz weg, wird 0 angenommen.

Zu solxpect gibt es einen Unterschied: Ich interpoliere innerhalb der Stunde in Teilschritten (ein Versuch, die geringen Zahlen am Tagesrand höher zu bekommen).
Zu den Zahlen: Bei mir im Westen (Grevenbroich) ging PV-Produktion heute um 05:40 Uhr los (Sonnenaufgang 05:32 Uhr). Erste Zahl um 06:00 Uhr passt also bei mir.

**Comment by EmanuelLoos** [comment]
Danke für die Antworten!

>  Lässt Du horizont ganz weg, wird 0 angenommen.

Wenn ich Horizont weglasse (auskommentiere), erhalte ich diese Fehlermeldung:
```
Exception in thread "main" java.lang.NullPointerException
	at de.garnix.pvprognose.PVPlane.getElevationCorrectedValue(PVPlane.java:111)
	at de.garnix.Main.main(Main.java:73)
```
Edit:
Mit `Balkon.horizon=0` funktioniert es. Allerdings verändert es eigenartigerweise kein Bisschen an den prognostizierten Werten. Irgendwelche Ideen, wie ich die Prognose näher an die tatsächlichen Werte bringen könnte? Das Muster der Abweichung wiederholt sich mehr oder weniger jeden Tag.
Die Differenz ist schon recht extrem:
```
TIME                 | WhGenFc | real
---------------------+---------+-----
2023-07-09T00:00:00Z |       0 |    0
2023-07-09T01:00:00Z |       0 |    0
2023-07-09T02:00:00Z |       0 |    0
2023-07-09T03:00:00Z |       0 |    0
2023-07-09T04:00:00Z |       0 |    0
2023-07-09T05:00:00Z |       0 |   10
2023-07-09T06:00:00Z |      20 |  110
2023-07-09T07:00:00Z |     241 |  390
2023-07-09T08:00:00Z |     477 |  600
2023-07-09T09:00:00Z |     572 |  650
2023-07-09T10:00:00Z |     560 |  810
2023-07-09T11:00:00Z |     465 |  760
2023-07-09T12:00:00Z |     309 |  550
2023-07-09T13:00:00Z |     145 |  370
2023-07-09T14:00:00Z |     133 |  200
2023-07-09T15:00:00Z |     113 |  110
2023-07-09T16:00:00Z |      83 |   70
2023-07-09T17:00:00Z |      77 |   50
2023-07-09T18:00:00Z |      37 |   80
2023-07-09T19:00:00Z |      41 |   50
2023-07-09T20:00:00Z |      31 |   40
2023-07-09T21:00:00Z |      21 |   40
2023-07-09T22:00:00Z |       4 |   10
2023-07-09T23:00:00Z |       0 |    0
---------------------+---------+-----
SUMME                |    3329 | 4900
```
solXpect kommt mit den gleichen Einstellungen näher heran:
```
Heute real | PVPrognose | solXpect
-----------+------------+---------
         0 |          0 |        0
        10 |          0 |        0
        40 |          1 |       17
       230 |        246 |      220
       400 |        501 |      406
       550 |        596 |      449
       800 |        571 |      590
       690 |        463 |      663
       590 |        313 |      571
       300 |        149 |      418
       170 |        124 |      212
       170 |        124 |      125
       110 |        115 |      112
        70 |        103 |       94
        60 |         84 |       73
        50 |         65 |       50
        40 |         39 |       26
        30 |         19 |        6
        10 |          3 |        0
         0 |          0 |        0
-----------+------------+---------
      4320 |       3516 |     4032
```

**Comment by EmanuelLoos** [comment]
@gvzdus @woheller69

Any idea why the values returned by PVPrognose and solXpect differ so much?

```
solXpect | PVPrognose |     real
---------+------------+---------
       0 |          0 |        0
       0 |          0 |        0
       0 |          0 |        0
      15 |        111 |       80
     198 |        596 |      410
     609 |        993 |     1210
    1539 |       3111 |     2430
    1268 |       5288 |     2620
    1211 |       6527 |     3770
    1846 |       7116 |     2610
    1580 |       7588 |     1760
     498 |       7452 |     2180
     967 |       6825 |     1310
    1517 |       5740 |     1220
    2705 |       4414 |     2080
    1525 |       3052 |      890
     917 |       1522 |     1020
     369 |        388 |      410
      22 |          0 |        ?
       0 |          0 |        ?
---------+------------+---------
   16786 |      60723 |    23990
```
![grafik](https://github.com/user-attachments/assets/1e862523-a2ee-47cd-af32-d5a7d72c2867)
![grafik](https://github.com/user-attachments/assets/b442f7d4-e1fa-46f6-8b9b-13fab5b2d164)
```
2024-08-05T06:00:00+02:00;0;15.6;0.0;0.0;0.0;60,3;-1,6
2024-08-05T07:00:00+02:00;111;16.1;0.0;12.1;12.0;71,8;7,0
2024-08-05T08:00:00+02:00;596;16.7;40.7;59.9;68.0;83,1;16,2
2024-08-05T09:00:00+02:00;993;18.1;39.9;95.8;110.0;94,8;25,6
2024-08-05T10:00:00+02:00;3111;19.5;307.2;179.6;334.0;107,5;34,8
2024-08-05T11:00:00+02:00;5288;21.5;583.7;186.8;555.0;122,5;43,4
2024-08-05T12:00:00+02:00;6527;22.1;656.4;203.1;683.0;140,8;50,4
2024-08-05T13:00:00+02:00;7116;23.8;660.9;225.3;752.0;163,5;54,8
2024-08-05T14:00:00+02:00;7588;24.7;707.7;223.0;806.0;188,7;55,5
2024-08-05T15:00:00+02:00;7452;25.4;711.8;216.6;793.0;212,5;52,2
2024-08-05T16:00:00+02:00;6825;25.6;690.3;203.3;725.0;232,2;45,8
2024-08-05T17:00:00+02:00;5740;25.4;634.7;187.6;610.0;248,0;37,6
2024-08-05T18:00:00+02:00;4414;25.0;566.4;166.2;475.0;261,3;28,5
2024-08-05T19:00:00+02:00;3052;24.7;508.3;137.1;342.0;273,2;19,1
2024-08-05T20:00:00+02:00;1522;23.8;353.7;100.1;188.0;284,5;9,8
2024-08-05T21:00:00+02:00;388;22.7;123.1;41.1;56.0;295,9;1,0
2024-08-05T22:00:00+02:00;0;21.7;0.0;0.0;0.0;307,9;-7,0
```
![grafik](https://github.com/user-attachments/assets/be70dd93-b8ce-410b-9b72-20a27b97c92b)
--------
![grafik](https://github.com/user-attachments/assets/e0594f71-7cb9-43d8-9146-0ff6acee35ec) ![grafik](https://github.com/user-attachments/assets/98205184-fbde-4afb-a796-3695ce0ae039)
```
$ cat ~/PVPrognose/solar.properties
#
# Position
longitude=15.86342
latitude=48.38149

planes=PV

# 0 = Nord, 90 Ost, ..
PV.azimuth=180
# Dachneigung
PV.tilt=18
# Kapazitaet DC
PV.capacity=9840
# Temperaturkoeffizient in % / °C, typisch: -0,4
PV.cellsTempCoeff=-0.4
PV.albedo=0.01
PV.diffuseEfficiency=0.9
# Inverter:
PV.inverter=FSP
# Horizont:
# The PVGis5 horizon model is used: 
# A list of equal wide sectors, starting from North clockwise, representing the obstacle elevation angle
# E.g.: 36 Values means: First value is the obstacle angle at 0-9.9°
# The elevation might be followed by a 't' and a transparency, to reflect e.g. thin obstacles or trees
# 10t0.2 means: Up to 10° sun elevation, only 20% transparency for direct radiation
PV.horizon=0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,4.2,7.7,10.7,13.3,15.4,16.9,17.9,18.2,17.9,16.9,15.4,13.3,10.7,7.7,4.2,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#0,0,0,0,0,2,5,7,8,8,8,9,9,9,9,10,10,10,10,20t0.15,20t0.15,31t0.1,31t0.1,31t0.1,36t0.1,36t0.1,36t0.1,36t0.1,36t0.1,36t0.1,36t0.1,36t0.1,36t0.1,20,10,0

FSP.maxpower=10000
```

**Comment by EmanuelLoos** [comment]
Ich verwende nun [open-meteo-solar-forecast](https://github.com/rany2/open-meteo-solar-forecast), womit ich momentan deutlich genauere Prognosen erhalte.
